"""add guideline graph nodes and edges

Revision ID: 0744758d2b7a
Revises: cd47a2d68c5e
Create Date: 2026-08-24 17:19:10.747926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0744758d2b7a"
down_revision: str | Sequence[str] | None = "cd47a2d68c5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guideline_graph_nodes",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "node_type",
            sa.Enum("CONDITION", "SYMPTOM", "RECOMMENDATION", name="graph_node_type"),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["guideline_documents.document_id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
        sa.UniqueConstraint("document_id", "node_type", "label", name="uq_graph_node_identity"),
    )
    op.create_index(
        op.f("ix_guideline_graph_nodes_document_id"),
        "guideline_graph_nodes",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "guideline_graph_edges",
        sa.Column("edge_id", sa.UUID(), nullable=False),
        sa.Column("source_node_id", sa.UUID(), nullable=False),
        sa.Column("target_node_id", sa.UUID(), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum("PRESENTS_WITH", "RECOMMENDS", name="graph_relation_type"),
            nullable=False,
        ),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["guideline_chunks.chunk_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["guideline_graph_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["guideline_graph_nodes.node_id"],
        ),
        sa.PrimaryKeyConstraint("edge_id"),
    )
    op.create_index(
        op.f("ix_guideline_graph_edges_chunk_id"),
        "guideline_graph_edges",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guideline_graph_edges_source_node_id"),
        "guideline_graph_edges",
        ["source_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guideline_graph_edges_target_node_id"),
        "guideline_graph_edges",
        ["target_node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_guideline_graph_edges_target_node_id"), table_name="guideline_graph_edges"
    )
    op.drop_index(
        op.f("ix_guideline_graph_edges_source_node_id"), table_name="guideline_graph_edges"
    )
    op.drop_index(op.f("ix_guideline_graph_edges_chunk_id"), table_name="guideline_graph_edges")
    op.drop_table("guideline_graph_edges")
    op.drop_index(op.f("ix_guideline_graph_nodes_document_id"), table_name="guideline_graph_nodes")
    op.drop_table("guideline_graph_nodes")
    # ### end Alembic commands ###

    # op.drop_table() does not drop the Postgres ENUM types it implicitly created; without
    # this, a subsequent upgrade fails with "type already exists" (see cd47a2d68c5e).
    bind = op.get_bind()
    postgresql.ENUM(name="graph_relation_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="graph_node_type").drop(bind, checkfirst=True)
