"""rename consultations to cases, extend for walkthrough data, add clinician oauth fields

Revision ID: 4c8ca44ce8e4
Revises: b99a2b1112ec
Create Date: 2026-09-22 18:33:16.677965

Hand-fixed after autogenerate -- see docs/build_log.md for the scope correction this
migration serves (walkthrough-case data replaces the old consultations/patient model).
Three real problems in the raw autogenerated script, fixed here:

1. Autogenerate only puts 'WALKTHROUGH' into the new `cases` table's Python-side Enum
   definition; it does not know how to ALTER the *existing* Postgres `source_type`
   type to add that value. Without an explicit ALTER TYPE, inserting a case with
   source_type='walkthrough' would fail at runtime with "invalid input value for
   enum source_type" even though the migration itself would apply cleanly.
2. It tried to `DROP TABLE consultations` while `case_precedent_vectors` still held a
   live foreign key to it -- Postgres would refuse. The FK (and the old column) must
   be dropped first.
3. It tried to `ADD COLUMN case_id ... NOT NULL` with no default to a table that may
   already have rows (from prior seed.py runs) -- would fail on non-empty tables.
   Since those old rows point at consultation rows this migration deletes anyway,
   this migration truncates case_precedent_vectors first rather than trying to
   backfill meaningless data.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c8ca44ce8e4"
down_revision: str | Sequence[str] | None = "b99a2b1112ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Postgres requires this to run before anything in the same transaction can use
    # the new value; nothing below inserts data, only declares column types, so this
    # is safe inside transactional DDL (PG12+).
    op.execute("ALTER TYPE source_type ADD VALUE IF NOT EXISTS 'WALKTHROUGH'")

    op.create_table(
        "cases",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column("external_case_ref", sa.String(length=50), nullable=True),
        sa.Column("transcript_or_summary", sa.Text(), nullable=False),
        sa.Column("doctor_disposition", sa.String(length=255), nullable=True),
        sa.Column("doctor_reasoning_notes", sa.Text(), nullable=True),
        # create_type=False: reuses the "source_type" type (just extended above),
        # not created here. See cd47a2d68c5e for why postgresql.ENUM must be used
        # directly rather than the generic sa.Enum.
        sa.Column(
            "source_type",
            postgresql.ENUM(
                "REAL_CONSULTATION",
                "ELICITATION_SESSION",
                "WALKTHROUGH",
                name="source_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("used_for_training", sa.Boolean(), nullable=False),
        sa.Column("used_for_holdout", sa.Boolean(), nullable=False),
        sa.Column("initial_impression", sa.Text(), nullable=True),
        sa.Column("questions_to_ask", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("examination_or_checks", sa.Text(), nullable=True),
        sa.Column("factors_toward_referral", sa.Text(), nullable=True),
        sa.Column("factors_against_referral", sa.Text(), nullable=True),
        sa.Column("flip_up", sa.Text(), nullable=True),
        sa.Column("flip_down", sa.Text(), nullable=True),
        sa.Column("red_flags", sa.Text(), nullable=True),
        sa.Column("confidence_notes", sa.Text(), nullable=True),
        sa.Column("general_rule", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["clinician_id"], ["clinicians.clinician_id"]),
        sa.PrimaryKeyConstraint("case_id"),
    )
    op.create_index(op.f("ix_cases_clinician_id"), "cases", ["clinician_id"], unique=False)

    # case_precedent_vectors: old rows point at consultation rows about to be
    # deleted, so they're meaningless regardless -- clear before restructuring
    # rather than trying to backfill a NOT NULL case_id with no sensible value.
    op.execute("TRUNCATE TABLE case_precedent_vectors")
    op.drop_constraint(
        op.f("case_precedent_vectors_consultation_id_fkey"),
        "case_precedent_vectors",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_case_precedent_vectors_consultation_id"), table_name="case_precedent_vectors"
    )
    op.drop_column("case_precedent_vectors", "consultation_id")
    op.add_column("case_precedent_vectors", sa.Column("case_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_case_precedent_vectors_case_id"), "case_precedent_vectors", ["case_id"]
    )
    op.create_foreign_key(
        op.f("case_precedent_vectors_case_id_fkey"),
        "case_precedent_vectors",
        "cases",
        ["case_id"],
        ["case_id"],
    )

    # Now safe: nothing references consultations any more.
    op.drop_index(op.f("ix_consultations_clinician_id"), table_name="consultations")
    op.drop_table("consultations")

    op.add_column("clinicians", sa.Column("google_sub", sa.String(length=255), nullable=True))
    op.add_column("clinicians", sa.Column("email", sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f("uq_clinicians_google_sub"), "clinicians", ["google_sub"])


def downgrade() -> None:
    op.drop_constraint(op.f("uq_clinicians_google_sub"), "clinicians", type_="unique")
    op.drop_column("clinicians", "email")
    op.drop_column("clinicians", "google_sub")

    op.create_table(
        "consultations",
        sa.Column("consultation_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column("patient_ref", sa.String(length=255), nullable=False),
        sa.Column("transcript_or_summary", sa.Text(), nullable=False),
        sa.Column("doctor_disposition", sa.String(length=255), nullable=True),
        sa.Column("doctor_reasoning_notes", sa.Text(), nullable=True),
        sa.Column(
            "source_type",
            postgresql.ENUM(
                "REAL_CONSULTATION",
                "ELICITATION_SESSION",
                "WALKTHROUGH",
                name="source_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("used_for_training", sa.Boolean(), nullable=False),
        sa.Column("used_for_holdout", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.clinician_id"],
            name=op.f("consultations_clinician_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("consultation_id", name=op.f("consultations_pkey")),
    )
    op.create_index(
        op.f("ix_consultations_clinician_id"), "consultations", ["clinician_id"], unique=False
    )

    op.execute("TRUNCATE TABLE case_precedent_vectors")
    op.drop_constraint(
        op.f("case_precedent_vectors_case_id_fkey"), "case_precedent_vectors", type_="foreignkey"
    )
    op.drop_index(op.f("ix_case_precedent_vectors_case_id"), table_name="case_precedent_vectors")
    op.drop_column("case_precedent_vectors", "case_id")
    op.add_column(
        "case_precedent_vectors",
        sa.Column("consultation_id", sa.UUID(), nullable=False),
    )
    op.create_index(
        op.f("ix_case_precedent_vectors_consultation_id"),
        "case_precedent_vectors",
        ["consultation_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("case_precedent_vectors_consultation_id_fkey"),
        "case_precedent_vectors",
        "consultations",
        ["consultation_id"],
        ["consultation_id"],
    )

    op.drop_index(op.f("ix_cases_clinician_id"), table_name="cases")
    op.drop_table("cases")

    # Not removing 'walkthrough' from the source_type enum: Postgres has no simple
    # ALTER TYPE ... DROP VALUE, only a full type recreation, which isn't worth it
    # for a downgrade path in a dev-stage project. The stray value is harmless.
