"""phase j consent model and consult feedback source type

Revision ID: 88f4329e360f
Revises: 4c8ca44ce8e4
Create Date: 2026-10-06 15:11:56.050509

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88f4329e360f"
down_revision: str | Sequence[str] | None = "4c8ca44ce8e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Alembic's autogenerate doesn't detect new values on an existing Postgres
    ENUM type (same gotcha as every prior migration in this project that
    extended one) -- added by hand. SQLAlchemy's Enum type stores the Python
    enum MEMBER NAME, not its .value, so these must be uppercase to match
    how the original types were created (cd47a2d68c5e).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consent_registry", sa.Column("reference_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###

    op.execute("ALTER TYPE source_type ADD VALUE IF NOT EXISTS 'CONSULT_FEEDBACK'")
    op.execute("ALTER TYPE consent_subject_type ADD VALUE IF NOT EXISTS 'WALKTHROUGH_RECORDING'")
    op.execute(
        "ALTER TYPE consent_subject_type ADD VALUE IF NOT EXISTS 'PATIENT_RECORDING_SESSION'"
    )


def downgrade() -> None:
    """Downgrade schema.

    Postgres has no simple "drop one enum value" -- same limitation noted in
    every prior migration that added one. A real rollback of the enum values
    themselves would need the full type-rebuild dance (new type, cast
    existing columns, drop old type, rename); not implemented here since
    nothing in this migration writes data using the new values. Column drop
    is a real, safe rollback.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consent_registry", "reference_id")
    # ### end Alembic commands ###
