"""add redaction summary to ingestion queue

Revision ID: b99a2b1112ec
Revises: ff3ae353ea3c
Create Date: 2026-08-24 19:19:05.789772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b99a2b1112ec"
down_revision: str | Sequence[str] | None = "ff3ae353ea3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: existing rows need a value for this new NOT NULL
    # column. Only applies at the DB level for pre-existing rows; new rows get their
    # value from the ORM model's default=dict instead.
    op.add_column(
        "ingestion_queue",
        sa.Column(
            "redaction_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingestion_queue", "redaction_summary")
    # ### end Alembic commands ###
