"""create initial schema

Revision ID: cd47a2d68c5e
Revises:
Create Date: 2026-08-24 16:18:30.947949

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd47a2d68c5e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector columns below (guideline_chunks.embedding, case_precedent_vectors.embedding)
    # require this extension to exist before their tables are created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinicians",
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("specialty", sa.String(length=255), nullable=True),
        sa.Column("credentials", sa.Text(), nullable=True),
        sa.Column("standing_protocols_ref", sa.Text(), nullable=True),
        sa.Column("consent_status", sa.String(length=50), nullable=False),
        sa.Column("consent_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("clinician_id"),
    )
    op.create_table(
        "guideline_documents",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("edition", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column(
            "actor", sa.Enum("SYSTEM", "CLINICIAN", "ADMIN", name="audit_actor"), nullable=False
        ),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("reference_table", sa.String(length=100), nullable=True),
        sa.Column("reference_id", sa.String(length=255), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.clinician_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(op.f("ix_audit_log_clinician_id"), "audit_log", ["clinician_id"], unique=False)
    op.create_table(
        "consent_registry",
        sa.Column("consent_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum("CLINICIAN", "PATIENT_DATA_BATCH", name="consent_subject_type"),
            nullable=False,
        ),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.clinician_id"],
        ),
        sa.PrimaryKeyConstraint("consent_id"),
    )
    op.create_index(
        op.f("ix_consent_registry_clinician_id"), "consent_registry", ["clinician_id"], unique=False
    )
    op.create_table(
        "consultations",
        sa.Column("consultation_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column("patient_ref", sa.String(length=255), nullable=False),
        sa.Column("transcript_or_summary", sa.Text(), nullable=False),
        sa.Column("doctor_disposition", sa.String(length=255), nullable=True),
        sa.Column("doctor_reasoning_notes", sa.Text(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("REAL_CONSULTATION", "ELICITATION_SESSION", name="source_type"),
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("used_for_training", sa.Boolean(), nullable=False),
        sa.Column("used_for_holdout", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.clinician_id"],
        ),
        sa.PrimaryKeyConstraint("consultation_id"),
    )
    op.create_index(
        op.f("ix_consultations_clinician_id"), "consultations", ["clinician_id"], unique=False
    )
    op.create_table(
        "guideline_chunks",
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["guideline_documents.document_id"],
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(
        op.f("ix_guideline_chunks_document_id"), "guideline_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "interaction_log",
        sa.Column("interaction_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("LEARNING", "CONSULTING_SANDBOX", name="interaction_mode"),
            nullable=False,
        ),
        sa.Column("input_case_ref", sa.String(length=255), nullable=False),
        sa.Column("draft_disposition", sa.Text(), nullable=True),
        sa.Column("final_disposition", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("guideline_conflict_flag", sa.Boolean(), nullable=False),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("explanation_ref", sa.String(length=255), nullable=True),
        sa.Column(
            "clinician_action",
            sa.Enum("APPROVED", "CORRECTED", "ESCALATED_REVIEW", name="clinician_action"),
            nullable=True,
        ),
        sa.Column("clinician_correction_notes", sa.Text(), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.clinician_id"],
        ),
        sa.PrimaryKeyConstraint("interaction_id"),
    )
    op.create_index(
        op.f("ix_interaction_log_clinician_id"), "interaction_log", ["clinician_id"], unique=False
    )
    op.create_table(
        "case_precedent_vectors",
        sa.Column("vector_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column("consultation_id", sa.UUID(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.clinician_id"],
        ),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultations.consultation_id"],
        ),
        sa.PrimaryKeyConstraint("vector_id"),
    )
    op.create_index(
        op.f("ix_case_precedent_vectors_clinician_id"),
        "case_precedent_vectors",
        ["clinician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_precedent_vectors_consultation_id"),
        "case_precedent_vectors",
        ["consultation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_case_precedent_vectors_consultation_id"), table_name="case_precedent_vectors"
    )
    op.drop_index(
        op.f("ix_case_precedent_vectors_clinician_id"), table_name="case_precedent_vectors"
    )
    op.drop_table("case_precedent_vectors")
    op.drop_index(op.f("ix_interaction_log_clinician_id"), table_name="interaction_log")
    op.drop_table("interaction_log")
    op.drop_index(op.f("ix_guideline_chunks_document_id"), table_name="guideline_chunks")
    op.drop_table("guideline_chunks")
    op.drop_index(op.f("ix_consultations_clinician_id"), table_name="consultations")
    op.drop_table("consultations")
    op.drop_index(op.f("ix_consent_registry_clinician_id"), table_name="consent_registry")
    op.drop_table("consent_registry")
    op.drop_index(op.f("ix_audit_log_clinician_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("guideline_documents")
    op.drop_table("clinicians")
    # ### end Alembic commands ###

    # op.drop_table() does not drop the Postgres ENUM types it implicitly created; without
    # this, a subsequent upgrade fails with "type already exists".
    bind = op.get_bind()
    postgresql.ENUM(name="audit_actor").drop(bind, checkfirst=True)
    postgresql.ENUM(name="consent_subject_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="source_type").drop(bind, checkfirst=True)
    postgresql.ENUM(name="interaction_mode").drop(bind, checkfirst=True)
    postgresql.ENUM(name="clinician_action").drop(bind, checkfirst=True)
