"""add ingestion queue

Revision ID: ff3ae353ea3c
Revises: 0744758d2b7a
Create Date: 2026-08-24 18:44:11.837452

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff3ae353ea3c"
down_revision: str | Sequence[str] | None = "0744758d2b7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_queue",
        sa.Column("ingestion_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        # create_type=False: reuses the "source_type" enum type that the initial
        # migration already created for consultations.source_type. Must use the
        # postgresql-specific ENUM class directly: create_type=False on the generic
        # sa.Enum is not reliably forwarded through dialect adaptation.
        sa.Column(
            "source_type",
            postgresql.ENUM(
                "REAL_CONSULTATION",
                "ELICITATION_SESSION",
                name="source_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RECEIVED", "PROCESSED", "FAILED", name="ingestion_status"),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.clinician_id"],
        ),
        sa.PrimaryKeyConstraint("ingestion_id"),
        sa.UniqueConstraint(
            "clinician_id", "idempotency_key", name="uq_ingestion_queue_clinician_idempotency_key"
        ),
    )
    op.create_index(
        op.f("ix_ingestion_queue_clinician_id"), "ingestion_queue", ["clinician_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_queue_clinician_id"), table_name="ingestion_queue")
    op.drop_table("ingestion_queue")
    # ### end Alembic commands ###

    # op.drop_table() does not drop the Postgres ENUM type it implicitly created for
    # `status` (see cd47a2d68c5e). Not dropping "source_type" here — it's owned by
    # the initial migration (consultations.source_type), reused via create_type=False
    # above, not created by this migration.
    postgresql.ENUM(name="ingestion_status").drop(op.get_bind(), checkfirst=True)
